/*
 Navicat Premium Data Transfer

 Source Server         : 47.104.97.30
 Source Server Type    : MySQL
 Source Server Version : 50636
 Source Host           : 47.104.97.30:3306
 Source Schema         : cuizeyun

 Target Server Type    : MySQL
 Target Server Version : 50636
 File Encoding         : 65001

 Date: 17/12/2021 18:12:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for express
-- ----------------------------
DROP TABLE IF EXISTS `express`;
CREATE TABLE `express`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1149 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of express
-- ----------------------------
INSERT INTO `express` VALUES (1, 'yuantong', '圆通速递');
INSERT INTO `express` VALUES (2, 'shunfeng', '顺丰速运');
INSERT INTO `express` VALUES (3, 'yunda', '韵达快递');
INSERT INTO `express` VALUES (4, 'zhongtong', '中通快递');
INSERT INTO `express` VALUES (5, 'youzhengguonei', '邮政快递包裹');
INSERT INTO `express` VALUES (6, 'jd', '京东物流');
INSERT INTO `express` VALUES (7, 'shentong', '申通快递');
INSERT INTO `express` VALUES (8, 'huitongkuaidi', '百世快递');
INSERT INTO `express` VALUES (9, 'ems', 'EMS');
INSERT INTO `express` VALUES (10, 'jtexpress', '极兔速递');
INSERT INTO `express` VALUES (11, 'youzhengbk', '邮政标准快递');
INSERT INTO `express` VALUES (12, 'debangwuliu', '德邦');
INSERT INTO `express` VALUES (13, 'debangkuaidi', '德邦快递');
INSERT INTO `express` VALUES (14, 'baishiwuliu', '百世快运');
INSERT INTO `express` VALUES (15, 'zhaijisong', '宅急送');
INSERT INTO `express` VALUES (16, 'tiantian', '天天快递');
INSERT INTO `express` VALUES (17, 'yuantongkuaiyun', '圆通快运');
INSERT INTO `express` VALUES (18, 'youshuwuliu', '优速快递');
INSERT INTO `express` VALUES (19, 'yundakuaiyun', '韵达快运');
INSERT INTO `express` VALUES (20, 'dsukuaidi', 'D速快递');
INSERT INTO `express` VALUES (21, 'lntjs', '特急送');
INSERT INTO `express` VALUES (22, 'zhongtongguoji', '中通国际');
INSERT INTO `express` VALUES (23, 'zhongyouex', '众邮快递');
INSERT INTO `express` VALUES (24, 'annto', '安得物流');
INSERT INTO `express` VALUES (25, 'upsen', 'UPS-全球件');
INSERT INTO `express` VALUES (26, 'dhlen', 'DHL-全球件');
INSERT INTO `express` VALUES (27, 'zhongtongkuaiyun', '中通快运');
INSERT INTO `express` VALUES (28, 'dhl', 'DHL-中国件');
INSERT INTO `express` VALUES (29, 'shunfengkuaiyun', '顺丰快运');
INSERT INTO `express` VALUES (30, 'annengwuliu', '安能快运');
INSERT INTO `express` VALUES (31, 'danniao', '丹鸟');
INSERT INTO `express` VALUES (32, 'jinguangsudikuaijian', '京广速递');
INSERT INTO `express` VALUES (33, 'youzhengguoji', '国际包裹');
INSERT INTO `express` VALUES (34, 'suning', '苏宁物流');
INSERT INTO `express` VALUES (35, 'kuayue', '跨越速运');
INSERT INTO `express` VALUES (36, 'fedex', 'FedEx-国际件');
INSERT INTO `express` VALUES (37, 'usps', 'USPS');
INSERT INTO `express` VALUES (38, 'yuntrack', 'YUN TRACK');
INSERT INTO `express` VALUES (39, 'ups', 'UPS');
INSERT INTO `express` VALUES (40, 'emsguoji', 'EMS-国际件');
INSERT INTO `express` VALUES (41, 'shpost', '同城快寄');
INSERT INTO `express` VALUES (42, 'httx56', '汇通天下物流');
INSERT INTO `express` VALUES (43, 'zhimakaimen', '芝麻开门');
INSERT INTO `express` VALUES (44, 'disifang', '递四方');
INSERT INTO `express` VALUES (45, 'suer', '速尔快递');
INSERT INTO `express` VALUES (46, 'meiquick', '美快国际物流');
INSERT INTO `express` VALUES (47, 'ewe', 'EWE全球快递');
INSERT INTO `express` VALUES (48, 'rrs', '日日顺物流');
INSERT INTO `express` VALUES (49, 'wherexpess', '威盛快递');
INSERT INTO `express` VALUES (50, 'guotongkuaidi', '国通快递');
INSERT INTO `express` VALUES (51, 'kuaijiesudi', '快捷速递');
INSERT INTO `express` VALUES (52, 'emsbg', 'EMS包裹');
INSERT INTO `express` VALUES (53, 'japanposten', '日本（Japan Post）');
INSERT INTO `express` VALUES (54, 'fedexcn', 'Fedex-国际件-中文');
INSERT INTO `express` VALUES (55, 'longbanwuliu', '龙邦速递');
INSERT INTO `express` VALUES (56, 'wondersyd', '中邮速递');
INSERT INTO `express` VALUES (57, 'yimidida', '壹米滴答');
INSERT INTO `express` VALUES (58, 'jiayunmeiwuliu', '加运美');
INSERT INTO `express` VALUES (59, 'jiuyescm', '九曳供应链');
INSERT INTO `express` VALUES (60, 'chinaicip', '卓志速运');
INSERT INTO `express` VALUES (61, 'zhongyouwuliu', '中邮物流');
INSERT INTO `express` VALUES (62, 'weitepai', '微特派');
INSERT INTO `express` VALUES (63, 'yw56', '燕文物流');
INSERT INTO `express` VALUES (64, 'rlgaus', '澳洲飞跃物流');
INSERT INTO `express` VALUES (65, 'zjstky', '苏通快运');
INSERT INTO `express` VALUES (66, 'xinfengwuliu', '信丰物流');
INSERT INTO `express` VALUES (67, 'ubonex', '优邦速运');
INSERT INTO `express` VALUES (68, 'tnt', 'TNT');
INSERT INTO `express` VALUES (69, 'guangdongyouzhengwuliu', '广东邮政');
INSERT INTO `express` VALUES (70, 'lianhaowuliu', '联昊通');
INSERT INTO `express` VALUES (71, 'aliexpress', '无忧物流');
INSERT INTO `express` VALUES (72, 'quanfengkuaidi', '全峰快递');
INSERT INTO `express` VALUES (73, 'lianbangkuaidien', '联邦快递-英文');
INSERT INTO `express` VALUES (74, 'doortodoor', 'CJ物流');
INSERT INTO `express` VALUES (75, 'subida', '速必达');
INSERT INTO `express` VALUES (76, 'suteng', '速腾快递');
INSERT INTO `express` VALUES (77, 'zhaojin', '招金精炼');
INSERT INTO `express` VALUES (78, 'stosolution', '申通国际');
INSERT INTO `express` VALUES (79, 'tnten', 'TNT-全球件');
INSERT INTO `express` VALUES (80, 'yuxinwuliu', '宇鑫物流');
INSERT INTO `express` VALUES (81, 'sxjdfreight', '顺心捷达');
INSERT INTO `express` VALUES (82, 'dpd', 'DPD');
INSERT INTO `express` VALUES (83, 'zengyisudi', '增益速递');
INSERT INTO `express` VALUES (84, 'santaisudi', '三态速递');
INSERT INTO `express` VALUES (85, 'fastgoexpress', '速派快递');
INSERT INTO `express` VALUES (86, 'xlobo', 'Xlobo贝海国际');
INSERT INTO `express` VALUES (87, 'uszcn', '转运中国');
INSERT INTO `express` VALUES (88, 'lianbangkuaidi', '联邦快递');
INSERT INTO `express` VALUES (89, 'tianma', '天马迅达');
INSERT INTO `express` VALUES (90, 'gslhkd', '联合快递');
INSERT INTO `express` VALUES (91, 'cosco', '中远e环球');
INSERT INTO `express` VALUES (92, 'flyway', '程光快递');
INSERT INTO `express` VALUES (93, 'fedexus', 'FedEx-美国件');
INSERT INTO `express` VALUES (94, 'sanhuwuliu', '叁虎物流');
INSERT INTO `express` VALUES (95, 'emsinten', 'EMS-国际件-英文');
INSERT INTO `express` VALUES (96, 'yuntong', '运通速运');
INSERT INTO `express` VALUES (97, 'tntau', 'TNT Australia');
INSERT INTO `express` VALUES (98, 'pingandatengfei', '平安达腾飞');
INSERT INTO `express` VALUES (99, 'savor', '海信物流');
INSERT INTO `express` VALUES (100, 'jingdongkuaiyun', '京东快运');
INSERT INTO `express` VALUES (101, 'rufengda', '如风达');
INSERT INTO `express` VALUES (102, 'sdto', '速达通');
INSERT INTO `express` VALUES (103, 'auspost', '澳大利亚(Australia Post)');
INSERT INTO `express` VALUES (104, 'anxindakuaixi', '安信达');
INSERT INTO `express` VALUES (105, 'auexpress', '澳邮中国快运');
INSERT INTO `express` VALUES (106, 'aramex', 'Aramex');
INSERT INTO `express` VALUES (107, 'zhengyikuaidi', '鑫正一快递');
INSERT INTO `express` VALUES (108, 'banma', '斑马物流');
INSERT INTO `express` VALUES (109, 'shenghuiwuliu', '盛辉物流');
INSERT INTO `express` VALUES (110, 'epanex', '泛捷国际速递');
INSERT INTO `express` VALUES (111, 'arkexpress', '方舟速递');
INSERT INTO `express` VALUES (112, 'youyou', '优优速递');
INSERT INTO `express` VALUES (113, 'zhongtiewuliu', '中铁飞豹');
INSERT INTO `express` VALUES (114, 'zhuanyunsifang', '转运四方');
INSERT INTO `express` VALUES (115, 'btexpress', '邦泰快运');
INSERT INTO `express` VALUES (116, 'ztky', '中铁快运');
INSERT INTO `express` VALUES (117, 'transrush', 'TransRush');
INSERT INTO `express` VALUES (118, 'tiandihuayu', '天地华宇');
INSERT INTO `express` VALUES (119, 'nsf', '新顺丰（NSF）');
INSERT INTO `express` VALUES (120, 'idamalu', '大马鹿');
INSERT INTO `express` VALUES (121, 'la911', '鼎润物流');
INSERT INTO `express` VALUES (122, 'anxl', '安迅物流');
INSERT INTO `express` VALUES (123, 'ftd', '富腾达国际货运');
INSERT INTO `express` VALUES (124, 'unitedex', '联合速运');
INSERT INTO `express` VALUES (125, 'youban', '邮邦国际');
INSERT INTO `express` VALUES (126, 'gls', 'GLS');
INSERT INTO `express` VALUES (127, 'bsht', '百事亨通');
INSERT INTO `express` VALUES (128, 'gotoubi', 'UBI Australia');
INSERT INTO `express` VALUES (129, 'hkpost', '中国香港(HongKong Post)');
INSERT INTO `express` VALUES (130, 'crazyexpress', '疯狂快递');
INSERT INTO `express` VALUES (131, 'jinan', '金岸物流');
INSERT INTO `express` VALUES (132, 'datianwuliu', '大田物流');
INSERT INTO `express` VALUES (133, 'bpost', '比利时（Bpost）');
INSERT INTO `express` VALUES (134, 'ocs', 'OCS');
INSERT INTO `express` VALUES (135, 'polarexpress', '极地快递');
INSERT INTO `express` VALUES (136, 'huisenky', '汇森速运');
INSERT INTO `express` VALUES (137, 'bazirim', '皮牙子快递');
INSERT INTO `express` VALUES (138, 'qhxyyg', '雪域易购');
INSERT INTO `express` VALUES (139, 'yuantongguoji', '圆通国际');
INSERT INTO `express` VALUES (140, 'wanxiangwuliu', '万象物流');
INSERT INTO `express` VALUES (141, 'ane66', '安能快递');
INSERT INTO `express` VALUES (142, 'qinyuan', '秦远物流');
INSERT INTO `express` VALUES (143, 'peru', '秘鲁(SERPOST)');
INSERT INTO `express` VALUES (144, 'zhaijibian', '宅急便');
INSERT INTO `express` VALUES (145, 'superb', 'Superb Grace');
INSERT INTO `express` VALUES (146, 'sfwl', '盛丰物流');
INSERT INTO `express` VALUES (147, 'sunjex', '新杰物流');
INSERT INTO `express` VALUES (148, 'zhonghuan', '中环快递');
INSERT INTO `express` VALUES (149, 'lijisong', '成都立即送');
INSERT INTO `express` VALUES (150, 'ecmscn', '易客满');
INSERT INTO `express` VALUES (151, 'newzealand', '新西兰（New Zealand Post）');
INSERT INTO `express` VALUES (152, 'highsince', 'Highsince');
INSERT INTO `express` VALUES (153, 'changjiang', '长江国际速递');
INSERT INTO `express` VALUES (154, 'baifudongfang', '百福东方');
INSERT INTO `express` VALUES (155, 'aae', 'AAE-中国件');
INSERT INTO `express` VALUES (156, 'jiayiwuliu', '佳怡物流');
INSERT INTO `express` VALUES (157, 'jxfex', '集先锋快递');
INSERT INTO `express` VALUES (158, 'dekuncn', '德坤物流');
INSERT INTO `express` VALUES (159, 'hd', '宏递快运');
INSERT INTO `express` VALUES (160, 'chukou1', '出口易');
INSERT INTO `express` VALUES (161, 'austa', 'Austa国际速递');
INSERT INTO `express` VALUES (162, 'xynyc', '新元国际');
INSERT INTO `express` VALUES (163, 'coe', 'COE');
INSERT INTO `express` VALUES (164, 'lbex', '龙邦物流');
INSERT INTO `express` VALUES (165, 'guexp', '全联速运');
INSERT INTO `express` VALUES (166, 'zhongsukuaidi', '中速快递');
INSERT INTO `express` VALUES (167, 'est365', '东方汇');
INSERT INTO `express` VALUES (168, 'sut56', '速通物流');
INSERT INTO `express` VALUES (169, 'shangqiao56', '商桥物流');
INSERT INTO `express` VALUES (170, 'yuananda', '源安达');
INSERT INTO `express` VALUES (171, 'hrex', '锦程快递');
INSERT INTO `express` VALUES (172, 'adapost', '安达速递');
INSERT INTO `express` VALUES (173, 'huanqiu', '环球速运');
INSERT INTO `express` VALUES (174, 'ucs', '合众速递(UCS）');
INSERT INTO `express` VALUES (175, 'tstexp', 'TST速运通');
INSERT INTO `express` VALUES (176, 'canpost', '加拿大(Canada Post)');
INSERT INTO `express` VALUES (177, 'huangmajia', '黄马甲');
INSERT INTO `express` VALUES (178, 'valueway', '美通');
INSERT INTO `express` VALUES (179, 'colissimo', '法国小包（colissimo）');
INSERT INTO `express` VALUES (180, 'ztcce', '中途速递');
INSERT INTO `express` VALUES (181, 'efs', 'EFS Post（平安快递）');
INSERT INTO `express` VALUES (182, 'passerbyaexpress', '顺捷美中速递');
INSERT INTO `express` VALUES (183, 'qexpress', '易达通快递');
INSERT INTO `express` VALUES (184, 'wanjiawuliu', '万家物流');
INSERT INTO `express` VALUES (185, 'jgwl', '景光物流');
INSERT INTO `express` VALUES (186, 'sendtochina', '速递中国');
INSERT INTO `express` VALUES (187, 'cnexps', 'CNE');
INSERT INTO `express` VALUES (188, 'postnl', '荷兰邮政(PostNL international registered mail)');
INSERT INTO `express` VALUES (189, 'emsen', 'EMS-英文');
INSERT INTO `express` VALUES (190, 'hnht56', '鸿泰物流');
INSERT INTO `express` VALUES (191, 'fujisuyun', '富吉速运');
INSERT INTO `express` VALUES (192, 'sagawa', '佐川急便');
INSERT INTO `express` VALUES (193, 'aotsd', '澳天速运');
INSERT INTO `express` VALUES (194, 'exfresh', '安鲜达');
INSERT INTO `express` VALUES (195, 'ftky365', '丰通快运');
INSERT INTO `express` VALUES (196, 'cyxfx', '小飞侠速递');
INSERT INTO `express` VALUES (197, 'zlink', '三真驿道');
INSERT INTO `express` VALUES (198, 'farlogistis', '泛远国际物流');
INSERT INTO `express` VALUES (199, 'deutschepost', '德国(Deutsche Post)');
INSERT INTO `express` VALUES (200, 'chnexp', '中翼国际物流');
INSERT INTO `express` VALUES (201, 'lfexpress', '龙枫国际快递');
INSERT INTO `express` VALUES (202, 'dfwl', '达发物流');
INSERT INTO `express` VALUES (203, 'gdkjk56', '快捷快物流');
INSERT INTO `express` VALUES (204, 'hmus', '华美快递');
INSERT INTO `express` VALUES (205, 'hengluwuliu', '恒路物流');
INSERT INTO `express` VALUES (206, 'hac56', '瀚朝物流');
INSERT INTO `express` VALUES (207, 'dhlde', 'DHL-德国件（DHL Deutschland）');
INSERT INTO `express` VALUES (208, 'jialidatong', '嘉里大通');
INSERT INTO `express` VALUES (209, 'ydhex', 'YDH');
INSERT INTO `express` VALUES (210, 'dpex', 'DPEX');
INSERT INTO `express` VALUES (211, 'timelytitan', 'Titan泰坦国际速递');
INSERT INTO `express` VALUES (212, 'tzky', '铁中快运');
INSERT INTO `express` VALUES (213, 'yuanfeihangwuliu', '原飞航');
INSERT INTO `express` VALUES (214, 'ztong', '智通物流');
INSERT INTO `express` VALUES (215, 'jumstc', '聚盟共建');
INSERT INTO `express` VALUES (216, 'postserv', '台湾（中华邮政）');
INSERT INTO `express` VALUES (217, 'postnlcn', '荷兰邮政-中文(PostNL international registered mail)');
INSERT INTO `express` VALUES (218, 'canpar', 'Canpar');
INSERT INTO `express` VALUES (219, 'parcelforce', '英国大包、EMS（Parcel Force）');
INSERT INTO `express` VALUES (220, 'stoexpress', '美国申通');
INSERT INTO `express` VALUES (221, 'synship', 'SYNSHIP快递');
INSERT INTO `express` VALUES (222, 'ubuy', '德国优拜物流');
INSERT INTO `express` VALUES (223, 'wykjt', '51跨境通');
INSERT INTO `express` VALUES (224, 'xdexpress', '迅达速递');
INSERT INTO `express` VALUES (225, 'hexinexpress', '合心速递');
INSERT INTO `express` VALUES (226, 'hermes', 'Hermes');
INSERT INTO `express` VALUES (227, 'airpak', 'airpak expresss');
INSERT INTO `express` VALUES (228, 'correosdees', '西班牙(Correos de Espa?a)');
INSERT INTO `express` VALUES (229, 'longcps', '加拿大龙行速运');
INSERT INTO `express` VALUES (230, 'oneexpress', '一速递');
INSERT INTO `express` VALUES (231, 'shunfenghk', '顺丰-繁体');
INSERT INTO `express` VALUES (232, 'longfx', 'LUCFLOW EXPRESS');
INSERT INTO `express` VALUES (233, 'nebuex', '星云速递');
INSERT INTO `express` VALUES (234, 'auod', '澳德物流');
INSERT INTO `express` VALUES (235, 'dhlecommerce', 'dhl小包');
INSERT INTO `express` VALUES (236, 'postnlchina', '荷兰邮政-中国件');
INSERT INTO `express` VALUES (237, 'ypsd', '壹品速递');
INSERT INTO `express` VALUES (238, 'cnpex', 'CNPEX中邮快递');
INSERT INTO `express` VALUES (239, 'shipgce', '飞洋快递');
INSERT INTO `express` VALUES (240, 'csuivi', '法国(La Poste)');
INSERT INTO `express` VALUES (241, 'ueq', 'UEQ快递');
INSERT INTO `express` VALUES (242, 'ytkd', '运通中港快递');
INSERT INTO `express` VALUES (243, 'com1express', '商壹国际物流');
INSERT INTO `express` VALUES (244, 'jiajiwuliu', '佳吉快运');
INSERT INTO `express` VALUES (245, 'ckeex', '城晓国际快递');
INSERT INTO `express` VALUES (246, 'beckygo', '佰麒快递');
INSERT INTO `express` VALUES (247, 'exsuda', 'E速达');
INSERT INTO `express` VALUES (248, 'italiane', '意大利(Poste Italiane)');
INSERT INTO `express` VALUES (249, 'cht361', '诚和通');
INSERT INTO `express` VALUES (250, 'baitengwuliu', '百腾物流');
INSERT INTO `express` VALUES (251, 'signedexpress', '签收快递');
INSERT INTO `express` VALUES (252, 'ukrpostcn', '乌克兰邮政包裹');
INSERT INTO `express` VALUES (253, 'didasuyun', '递达速运');
INSERT INTO `express` VALUES (254, 'ndwl', '南方传媒物流');
INSERT INTO `express` VALUES (255, 'feiyuanvipshop', '飞远配送');
INSERT INTO `express` VALUES (256, 'asendiausa', 'Asendia USA');
INSERT INTO `express` VALUES (257, 'swisspost', '瑞士(Swiss Post)');
INSERT INTO `express` VALUES (258, 'uscbexpress', '易境达国际物流');
INSERT INTO `express` VALUES (259, 'hdcexpress', '汇达物流');
INSERT INTO `express` VALUES (260, 'maldives', '马尔代夫(Maldives Post)');
INSERT INTO `express` VALUES (261, 'newsway', '家家通快递');
INSERT INTO `express` VALUES (262, 'bdatong', '八达通');
INSERT INTO `express` VALUES (263, 'sundarexpress', '顺达快递');
INSERT INTO `express` VALUES (264, 'haidaibao', '海带宝');
INSERT INTO `express` VALUES (265, 'quanyikuaidi', '全一快递');
INSERT INTO `express` VALUES (266, 'yufeng', '御风速运');
INSERT INTO `express` VALUES (267, 'japanpost', '日本郵便');
INSERT INTO `express` VALUES (268, 'chszhonghuanguoji', 'CHS中环国际快递');
INSERT INTO `express` VALUES (269, 'dpexen', 'Toll');
INSERT INTO `express` VALUES (270, 'diantongkuaidi', '店通快递');
INSERT INTO `express` VALUES (271, 'qpost', '卡塔尔（Qatar Post）');
INSERT INTO `express` VALUES (272, 'zhonghuanus', '中环转运');
INSERT INTO `express` VALUES (273, 'di5pll', '递五方云仓');
INSERT INTO `express` VALUES (274, 'koreapost', '韩国（Korea Post）');
INSERT INTO `express` VALUES (275, 'xunsuexpress', '迅速快递');
INSERT INTO `express` VALUES (276, 'yangbaoguo', '洋包裹');
INSERT INTO `express` VALUES (277, 'yaofeikuaidi', '耀飞同城快递');
INSERT INTO `express` VALUES (278, 'dhlbenelux', 'DHL Benelux');
INSERT INTO `express` VALUES (279, 'dfkuaidi', '东风快递');
INSERT INTO `express` VALUES (280, 'ruidianyouzheng', '瑞典（Sweden Post）');
INSERT INTO `express` VALUES (281, 'youjia', '友家速递');
INSERT INTO `express` VALUES (282, 'yousutongda', '优速通达');
INSERT INTO `express` VALUES (283, 'bjemstckj', '北京EMS');
INSERT INTO `express` VALUES (284, 'emswuliu', 'EMS物流');
INSERT INTO `express` VALUES (285, 'yiex', '宜送物流');
INSERT INTO `express` VALUES (286, 'westwing', '西翼物流');
INSERT INTO `express` VALUES (287, 'yidatong', '易达通');
INSERT INTO `express` VALUES (288, 'cccc58', '中集冷云');
INSERT INTO `express` VALUES (289, 'bflg', '上海缤纷物流');
INSERT INTO `express` VALUES (290, 'hlyex', '好来运');
INSERT INTO `express` VALUES (291, 'pjbest', '品骏快递');
INSERT INTO `express` VALUES (292, 'ycgky', '远成快运');
INSERT INTO `express` VALUES (293, 'shangda', '上大物流');
INSERT INTO `express` VALUES (294, 'yizhengdasuyun', '一正达速运');
INSERT INTO `express` VALUES (295, 'koalaexp', '考拉速递');
INSERT INTO `express` VALUES (296, 'cameroon', '喀麦隆(CAMPOST)');
INSERT INTO `express` VALUES (297, 'jiacheng', '佳成快递 ');
INSERT INTO `express` VALUES (298, 'tnjex', '明通国际快递');
INSERT INTO `express` VALUES (299, 'xiyoug', '西游寄');
INSERT INTO `express` VALUES (300, 'nanjingshengbang', '晟邦物流');
INSERT INTO `express` VALUES (301, 'trakpak', 'TRAKPAK');
INSERT INTO `express` VALUES (302, 'tcat', '黑猫宅急便');
INSERT INTO `express` VALUES (303, 'yuanchengwuliu', '远成物流');
INSERT INTO `express` VALUES (304, 'yzswuliu', '亚洲顺物流');
INSERT INTO `express` VALUES (305, 'jssdt56', '时达通');
INSERT INTO `express` VALUES (306, 'chuanxiwuliu', '传喜物流');
INSERT INTO `express` VALUES (307, 'yafengsudi', '亚风速递');
INSERT INTO `express` VALUES (308, 'euasia', '欧亚专线');
INSERT INTO `express` VALUES (309, 'yingchao', '英超物流');
INSERT INTO `express` VALUES (310, 'heimao56', '黑猫速运');
INSERT INTO `express` VALUES (311, 'meixi', '美西快递');
INSERT INTO `express` VALUES (312, 'tmwexpress', '明达国际速递');
INSERT INTO `express` VALUES (313, 'rpx', 'rpx');
INSERT INTO `express` VALUES (314, 'quansu', '全速物流');
INSERT INTO `express` VALUES (315, 'hangrui', '上海航瑞货运');
INSERT INTO `express` VALUES (316, 'hkposten', '中国香港(HongKong Post)英文');
INSERT INTO `express` VALUES (317, 'jiajikuaidi', '佳吉快递');
INSERT INTO `express` VALUES (318, 'wedepot', 'wedepot物流');
INSERT INTO `express` VALUES (319, 'jdiex', 'JDIEX');
INSERT INTO `express` VALUES (320, 'malaysiapost', '马来西亚小包（Malaysia Post(Registered)）');
INSERT INTO `express` VALUES (321, 'anjie88', '安捷物流');
INSERT INTO `express` VALUES (322, 'spring56', '春风物流');
INSERT INTO `express` VALUES (323, 'feikangda', '飞康达');
INSERT INTO `express` VALUES (324, 'gsm', 'GSM');
INSERT INTO `express` VALUES (325, 'ganzhongnengda', '能达速递');
INSERT INTO `express` VALUES (326, 'uhi', '优海国际速递');
INSERT INTO `express` VALUES (327, 'yjhgo', '武汉优进汇');
INSERT INTO `express` VALUES (328, 'astexpress', '安世通快递');
INSERT INTO `express` VALUES (329, 'chinapostcb', '中邮电商');
INSERT INTO `express` VALUES (330, 'esinotrans', '中外运');
INSERT INTO `express` VALUES (331, 'shangcheng', '尚橙物流');
INSERT INTO `express` VALUES (332, 'emms', '澳州顺风快递');
INSERT INTO `express` VALUES (333, 'flysman', '飞力士物流');
INSERT INTO `express` VALUES (334, 'minghangkuaidi', '民航快递');
INSERT INTO `express` VALUES (335, 'yuntongkuaidi', '运通中港');
INSERT INTO `express` VALUES (336, 'dayangwuliu', '大洋物流');
INSERT INTO `express` VALUES (337, 'jiguang', '极光转运');
INSERT INTO `express` VALUES (338, 'singpost', '新加坡小包(Singapore Post)');
INSERT INTO `express` VALUES (339, 'zhongwaiyun', '中外运速递');
INSERT INTO `express` VALUES (340, 'driverfastgo', '老司机国际快递');
INSERT INTO `express` VALUES (341, 'gts', 'GTS快递');
INSERT INTO `express` VALUES (342, 'luben', '陆本速递 LUBEN EXPRESS');
INSERT INTO `express` VALUES (343, 'bht', 'BHT');
INSERT INTO `express` VALUES (344, 'qbexpress', '秦邦快运');
INSERT INTO `express` VALUES (345, 'yujiawl', '宇佳物流');
INSERT INTO `express` VALUES (346, 'dpdpoland', 'DPD Poland');
INSERT INTO `express` VALUES (347, 'yiqisong', '一起送');
INSERT INTO `express` VALUES (348, 'zdepost', '直德邮');
INSERT INTO `express` VALUES (349, 'amazoncnorder', '亚马逊中国订单');
INSERT INTO `express` VALUES (350, 'beebird', '锋鸟物流');
INSERT INTO `express` VALUES (351, 'cnspeedster', '速舟物流');
INSERT INTO `express` VALUES (352, 'feikuaida', '飞快达');
INSERT INTO `express` VALUES (353, 'ykouan', '洋口岸');
INSERT INTO `express` VALUES (354, 'gaticn', 'Gati-中文');
INSERT INTO `express` VALUES (355, 'morelink56', 'MoreLink');
INSERT INTO `express` VALUES (356, 'sd138', '泰国138国际物流');
INSERT INTO `express` VALUES (357, 'shunjiefengda', '顺捷丰达');
INSERT INTO `express` VALUES (358, 'tollpriority', 'Toll Priority(Toll Online)');
INSERT INTO `express` VALUES (359, 'topspeedex', '中运全速');
INSERT INTO `express` VALUES (360, 'trackparcel', 'track-parcel');
INSERT INTO `express` VALUES (361, 'wjkwl', '万家康物流');
INSERT INTO `express` VALUES (362, 'emonitoring', '波兰小包(Poczta Polska)');
INSERT INTO `express` VALUES (363, 'haihongwangsong', '海红网送');
INSERT INTO `express` VALUES (364, 'kingfreight', '货运皇');
INSERT INTO `express` VALUES (365, 'sffw', '丰网速运');
INSERT INTO `express` VALUES (366, 'ytchengnuoda', '承诺达');
INSERT INTO `express` VALUES (367, 'chuangyi', '创一快递');
INSERT INTO `express` VALUES (368, 'cllexpress', '澳通华人物流');
INSERT INTO `express` VALUES (369, 'jieanda', '捷安达');
INSERT INTO `express` VALUES (370, 'ydglobe', '云达通');
INSERT INTO `express` VALUES (371, 'cces', 'CCES/国通快递');
INSERT INTO `express` VALUES (372, 'kejie', '科捷物流');
INSERT INTO `express` VALUES (373, 'republic', '叙利亚(Syrian Post)');
INSERT INTO `express` VALUES (374, 'yongbangwuliu', '永邦国际物流');
INSERT INTO `express` VALUES (375, 'zsda56', '转瞬达集运');
INSERT INTO `express` VALUES (376, 'asendia', '阿森迪亚');
INSERT INTO `express` VALUES (377, 'bpostinter', '比利时国际(Bpost international)');
INSERT INTO `express` VALUES (378, 'guoeryue', '天天快物流');
INSERT INTO `express` VALUES (379, 'newgistics', 'Newgistics');
INSERT INTO `express` VALUES (380, 'pengyuanexpress', '鹏远国际速递');
INSERT INTO `express` VALUES (381, 'szyouzheng', '深圳邮政');
INSERT INTO `express` VALUES (382, 'ttkeurope', '天天欧洲物流');
INSERT INTO `express` VALUES (383, 'feibaokuaidi', '飞豹快递');
INSERT INTO `express` VALUES (384, 'india', '印度(India Post)');
INSERT INTO `express` VALUES (385, 'jiujiuwl', '久久物流');
INSERT INTO `express` VALUES (386, 'koreapostcn', '韩国邮政');
INSERT INTO `express` VALUES (387, 'lineone', '一号线');
INSERT INTO `express` VALUES (388, 'meiguokuaidi', '美国快递');
INSERT INTO `express` VALUES (389, 'postnlpacle', '荷兰包裹(PostNL International Parcels)');
INSERT INTO `express` VALUES (390, 'tykd', '天翼快递');
INSERT INTO `express` VALUES (391, 'yongchangwuliu', '永昌物流');
INSERT INTO `express` VALUES (392, 'bangsongwuliu', '邦送物流');
INSERT INTO `express` VALUES (393, 'gslexpress', '德尚国际速递');
INSERT INTO `express` VALUES (394, 'huiqiangkuaidi', '汇强快递');
INSERT INTO `express` VALUES (395, 'pcaexpress', 'PCA Express');
INSERT INTO `express` VALUES (396, 'runhengfeng', '全时速运');
INSERT INTO `express` VALUES (397, 'shenganwuliu', '圣安物流');
INSERT INTO `express` VALUES (398, 'stkd', '顺通快递');
INSERT INTO `express` VALUES (399, 'szshihuatong56', '世华通物流');
INSERT INTO `express` VALUES (400, 'taoplus', '淘布斯国际物流');
INSERT INTO `express` VALUES (401, 'thailand', '泰国（Thailand Thai Post）');
INSERT INTO `express` VALUES (402, 'yunfeng56', '韵丰物流');
INSERT INTO `express` VALUES (403, 'zlxdjwl', '中粮鲜到家物流');
INSERT INTO `express` VALUES (404, 'dindon', '叮咚澳洲转运');
INSERT INTO `express` VALUES (405, 'yuanzhijiecheng', '元智捷诚');
INSERT INTO `express` VALUES (406, 'abf', 'ABF');
INSERT INTO `express` VALUES (407, 'etong', 'E通速递');
INSERT INTO `express` VALUES (408, 'hongbeixin', '红背心');
INSERT INTO `express` VALUES (409, 'sccod', '丰程物流');
INSERT INTO `express` VALUES (410, 'zteexpress', 'ZTE中兴物流');
INSERT INTO `express` VALUES (411, 'chengpei', '河北橙配');
INSERT INTO `express` VALUES (412, 'ctoexp', '泰国中通CTO');
INSERT INTO `express` VALUES (413, 'homecourier', '如家国际快递');
INSERT INTO `express` VALUES (414, 'hongywl', '红远物流');
INSERT INTO `express` VALUES (415, 'jixianda', '急先达');
INSERT INTO `express` VALUES (416, 'juding', '聚鼎物流');
INSERT INTO `express` VALUES (417, 'nell', '尼尔快递');
INSERT INTO `express` VALUES (418, 'renrenex', '人人转运');
INSERT INTO `express` VALUES (419, '1ziton', '一智通');
INSERT INTO `express` VALUES (420, 'belgiumpost', '比利时(Belgium Post)');
INSERT INTO `express` VALUES (421, 'buytong', '百通物流');
INSERT INTO `express` VALUES (422, 'chinastarlogistics', '华欣物流');
INSERT INTO `express` VALUES (423, 'landmarkglobal', 'Landmark Global');
INSERT INTO `express` VALUES (424, 'lasership', 'LaserShip');
INSERT INTO `express` VALUES (425, 'mosuda', '魔速达');
INSERT INTO `express` VALUES (426, 'pochta', '俄罗斯邮政(Russian Post)');
INSERT INTO `express` VALUES (427, 'purolator', 'Purolator');
INSERT INTO `express` VALUES (428, 'wandougongzhu', '豌豆物流');
INSERT INTO `express` VALUES (429, 'wto56kj', '臣邦同城');
INSERT INTO `express` VALUES (430, 'ynztsy', '纵通速运');
INSERT INTO `express` VALUES (431, 'yundaexus', '美国云达');
INSERT INTO `express` VALUES (432, 'zhitengwuliu', '志腾物流');
INSERT INTO `express` VALUES (433, 'zhongchuan', '众川国际');
INSERT INTO `express` VALUES (434, 'zyzoom', '增速跨境 ');
INSERT INTO `express` VALUES (435, 'fastway', 'Fastway Ireland');
INSERT INTO `express` VALUES (436, 'gda', '安的快递');
INSERT INTO `express` VALUES (437, 'junfengguoji', '骏丰国际速递');
INSERT INTO `express` VALUES (438, 'latvia', '拉脱维亚(Latvijas Pasts)');
INSERT INTO `express` VALUES (439, 'nederlandpost', '荷兰速递(Nederland Post)');
INSERT INTO `express` VALUES (440, 'rrskx', '日日顺快线');
INSERT INTO `express` VALUES (441, 'sdsy888', '首达速运');
INSERT INTO `express` VALUES (442, 'slovenia', '斯洛文尼亚(Slovenia Post)');
INSERT INTO `express` VALUES (443, 'ukrpost', '乌克兰小包、大包(UkrPost)');
INSERT INTO `express` VALUES (444, 'wtdchina', '威时沛运货运');
INSERT INTO `express` VALUES (445, 'yhtlogistics', '宇航通物流');
INSERT INTO `express` VALUES (446, 'gooday365', '日日顺智慧物联');
INSERT INTO `express` VALUES (447, 'kazpost', '哈萨克斯坦(Kazpost)');
INSERT INTO `express` VALUES (448, 'kfwnet', '快服务');
INSERT INTO `express` VALUES (449, 'koreapostkr', '韩国邮政韩文');
INSERT INTO `express` VALUES (450, 'mmlogi', '猛犸速递');
INSERT INTO `express` VALUES (451, 'nntengda', '腾达速递');
INSERT INTO `express` VALUES (452, 'phlpost', '菲律宾（Philippine Postal）');
INSERT INTO `express` VALUES (453, 'sufengkuaidi', '速风快递');
INSERT INTO `express` VALUES (454, 'sxhongmajia', '红马甲物流');
INSERT INTO `express` VALUES (455, 'zhongtianwanyun', '中天万运');
INSERT INTO `express` VALUES (456, 'adaexpress', '明大快递');
INSERT INTO `express` VALUES (457, 'adp', 'ADP国际快递');
INSERT INTO `express` VALUES (458, 'alog', '心怡物流');
INSERT INTO `express` VALUES (459, 'aolau', 'AOL澳通速递');
INSERT INTO `express` VALUES (460, 'biaojikuaidi', '彪记快递');
INSERT INTO `express` VALUES (461, 'chronopostfra', '法国大包、EMS-法文（Chronopost France）');
INSERT INTO `express` VALUES (462, 'comexpress', '邦通国际');
INSERT INTO `express` VALUES (463, 'dpdgermany', 'DPD Germany');
INSERT INTO `express` VALUES (464, 'easyexpress', 'EASY EXPRESS');
INSERT INTO `express` VALUES (465, 'jiachenexpress', '佳辰国际速递');
INSERT INTO `express` VALUES (466, 'kaolaexpress', '考拉国际速递');
INSERT INTO `express` VALUES (467, 'lutong', '鲁通快运');
INSERT INTO `express` VALUES (468, 'onehcang', '一号仓');
INSERT INTO `express` VALUES (469, 'postdanmarken', '丹麦(Post Denmark)');
INSERT INTO `express` VALUES (470, 's2c', 'S2C');
INSERT INTO `express` VALUES (471, 'saiaodimmb', '赛澳递for买卖宝');
INSERT INTO `express` VALUES (472, 'sanzhi56', '三志物流');
INSERT INTO `express` VALUES (473, 'vps', '维普恩物流');
INSERT INTO `express` VALUES (474, 'yyexp', '西安运逸快递');
INSERT INTO `express` VALUES (475, 'zenzen', '三三国际物流');
INSERT INTO `express` VALUES (476, 'zf365', '珠峰速运');
INSERT INTO `express` VALUES (477, 'zrtl', '中融泰隆');
INSERT INTO `express` VALUES (478, 'zy100', '中远快运');
INSERT INTO `express` VALUES (479, 'a2u', 'A2U速递');
INSERT INTO `express` VALUES (480, 'benteng', '奔腾物流');
INSERT INTO `express` VALUES (481, 'boyol', '贝业物流');
INSERT INTO `express` VALUES (482, 'disifangau', '递四方澳洲');
INSERT INTO `express` VALUES (483, 'gongsuda', '共速达');
INSERT INTO `express` VALUES (484, 'hhair56', '华瀚快递');
INSERT INTO `express` VALUES (485, 'hltop', '海联快递');
INSERT INTO `express` VALUES (486, 'hpexpress', '海派国际速递');
INSERT INTO `express` VALUES (487, 'israelpost', '以色列(Israel Post)');
INSERT INTO `express` VALUES (488, 'jcsuda', '嘉诚速达');
INSERT INTO `express` VALUES (489, 'jingshun', '景顺物流');
INSERT INTO `express` VALUES (490, 'kcs', 'KCS');
INSERT INTO `express` VALUES (491, 'luckyfastex', '吉捷国际速递');
INSERT INTO `express` VALUES (492, 'pzhjst', '急顺通');
INSERT INTO `express` VALUES (493, 'saiaodi', '赛澳递');
INSERT INTO `express` VALUES (494, 'staky', '首通快运');
INSERT INTO `express` VALUES (495, 'sunspeedy', '新速航');
INSERT INTO `express` VALUES (496, 'szuem', '联运通物流');
INSERT INTO `express` VALUES (497, 'tjkjwl', '泰实货运');
INSERT INTO `express` VALUES (498, 'wuliuky', '五六快运');
INSERT INTO `express` VALUES (499, 'wuyuansudi', '伍圆速递');
INSERT INTO `express` VALUES (500, 'yourscm', '雅澳物流');
INSERT INTO `express` VALUES (501, 'yujtong', '宇捷通');
INSERT INTO `express` VALUES (502, 'ywexpress', '远为快递');
INSERT INTO `express` VALUES (503, 'zhuoshikuaiyun', '卓实快运');
INSERT INTO `express` VALUES (504, 'ajexpress', '捷记方舟');
INSERT INTO `express` VALUES (505, 'anjiekuaidi', '青岛安捷快递');
INSERT INTO `express` VALUES (506, 'ariesfar', '艾瑞斯远');
INSERT INTO `express` VALUES (507, 'ausexpress', '澳世速递');
INSERT INTO `express` VALUES (508, 'auvanda', '中联速递');
INSERT INTO `express` VALUES (509, 'baishiyp', '百世云配');
INSERT INTO `express` VALUES (510, 'ceskaposta', '捷克（?eská po?ta）');
INSERT INTO `express` VALUES (511, 'cnair', 'CNAIR');
INSERT INTO `express` VALUES (512, 'dongjun', '成都东骏物流');
INSERT INTO `express` VALUES (513, 'emirates', '阿联酋(Emirates Post)');
INSERT INTO `express` VALUES (514, 'fanyukuaidi', '凡宇快递');
INSERT INTO `express` VALUES (515, 'hkeex', '飞豹速递');
INSERT INTO `express` VALUES (516, 'hkems', '云邮跨境快递');
INSERT INTO `express` VALUES (517, 'huanqiuabc', '中国香港环球快运');
INSERT INTO `express` VALUES (518, 'ibuy8', '爱拜物流');
INSERT INTO `express` VALUES (519, 'leopard', '云豹国际货运');
INSERT INTO `express` VALUES (520, 'quanchuan56', '全川物流');
INSERT INTO `express` VALUES (521, 'quanritongkuaidi', '全日通');
INSERT INTO `express` VALUES (522, 'sofast56', '嗖一下同城快递');
INSERT INTO `express` VALUES (523, 'suijiawuliu', '穗佳物流');
INSERT INTO `express` VALUES (524, 'uluckex', '优联吉运');
INSERT INTO `express` VALUES (525, 'xyd666', '鑫远东速运');
INSERT INTO `express` VALUES (526, 'yiyou', '易邮速运');
INSERT INTO `express` VALUES (527, 'yuandun', '远盾物流');
INSERT INTO `express` VALUES (528, 'zjcy56', '创运物流');
INSERT INTO `express` VALUES (529, 'ztjieda', '泰捷达国际物流');
INSERT INTO `express` VALUES (530, 'ahdf', '德方物流');
INSERT INTO `express` VALUES (531, 'airgtc', '加拿大民航快递');
INSERT INTO `express` VALUES (532, 'belpost', '白俄罗斯(Belpochta)');
INSERT INTO `express` VALUES (533, 'bulgarian', '保加利亚（Bulgarian Posts）');
INSERT INTO `express` VALUES (534, 'citylink', 'City-Link');
INSERT INTO `express` VALUES (535, 'cloudexpress', 'CE易欧通国际速递');
INSERT INTO `express` VALUES (536, 'correoargentino', '阿根廷(Correo Argentina)');
INSERT INTO `express` VALUES (537, 'dadaoex', '大道物流');
INSERT INTO `express` VALUES (538, 'euexpress', 'EU-EXPRESS');
INSERT INTO `express` VALUES (539, 'express7th', '7号速递');
INSERT INTO `express` VALUES (540, 'ge2d', 'GE2D跨境物流');
INSERT INTO `express` VALUES (541, 'gttexpress', 'GTT EXPRESS快递');
INSERT INTO `express` VALUES (542, 'jiajiawl', '加佳物流');
INSERT INTO `express` VALUES (543, 'jindawuliu', '金大物流');
INSERT INTO `express` VALUES (544, 'khzto', '柬埔寨中通');
INSERT INTO `express` VALUES (545, 'ksudi', '快速递');
INSERT INTO `express` VALUES (546, 'kuaidawuliu', '快达物流');
INSERT INTO `express` VALUES (547, 'ledaowuliu', '楽道物流');
INSERT INTO `express` VALUES (548, 'lqht', '恒通快递');
INSERT INTO `express` VALUES (549, 'ltexp', '乐天速递');
INSERT INTO `express` VALUES (550, 'macao', '中国澳门(Macau Post)');
INSERT INTO `express` VALUES (551, 'malaysiaems', '马来西亚大包、EMS（Malaysia Post(parcel,EMS)）');
INSERT INTO `express` VALUES (552, 'polarisexpress', '北极星快运');
INSERT INTO `express` VALUES (553, 'sfpost', '曹操到');
INSERT INTO `express` VALUES (554, 'shanhuodidi', '闪货极速达');
INSERT INTO `express` VALUES (555, 'shunjieda', '顺捷达');
INSERT INTO `express` VALUES (556, 'thaizto', '泰国中通ZTO');
INSERT INTO `express` VALUES (557, 'tongdaxing', '通达兴物流');
INSERT INTO `express` VALUES (558, 'tunisia', '突尼斯EMS(Rapid-Poste)');
INSERT INTO `express` VALUES (559, 'uspscn', 'USPSCN');
INSERT INTO `express` VALUES (560, 'vietnam', '越南小包(Vietnam Posts)');
INSERT INTO `express` VALUES (561, 'winit', '万邑通');
INSERT INTO `express` VALUES (562, 'wotu', '渥途国际速运');
INSERT INTO `express` VALUES (563, 'xianglongyuntong', '祥龙运通物流');
INSERT INTO `express` VALUES (564, 'xiangteng', '翔腾物流');
INSERT INTO `express` VALUES (565, 'xilaikd', '西安喜来快递');
INSERT INTO `express` VALUES (566, 'yibangwuliu', '一邦速递');
INSERT INTO `express` VALUES (567, 'yidihui', '驿递汇速递');
INSERT INTO `express` VALUES (568, 'yinjiesudi', '银捷速递');
INSERT INTO `express` VALUES (569, 'yiouzhou', '易欧洲国际物流');
INSERT INTO `express` VALUES (570, 'yiqiguojiwuliu', '一柒国际物流');
INSERT INTO `express` VALUES (571, 'yisong', '宜送');
INSERT INTO `express` VALUES (572, 'yue777', '玥玛速运');
INSERT INTO `express` VALUES (573, 'zhongxinda', '忠信达');
INSERT INTO `express` VALUES (574, 'abcglobal', '全球快运');
INSERT INTO `express` VALUES (575, 'albania', '阿尔巴尼亚(Posta shqipatre)');
INSERT INTO `express` VALUES (576, 'anposten', '爱尔兰(An Post)');
INSERT INTO `express` VALUES (577, 'austria', '奥地利(Austrian Post)');
INSERT INTO `express` VALUES (578, 'bjqywl', '青云物流');
INSERT INTO `express` VALUES (579, 'chunfai', '中国香港骏辉物流');
INSERT INTO `express` VALUES (580, 'chunghwa56', '中骅物流');
INSERT INTO `express` VALUES (581, 'cnausu', '中澳速递');
INSERT INTO `express` VALUES (582, 'colombia', '哥伦比亚(4-72 La Red Postal de Colombia)');
INSERT INTO `express` VALUES (583, 'cpsair', '华中快递');
INSERT INTO `express` VALUES (584, 'dande56', '丹递56');
INSERT INTO `express` VALUES (585, 'dechuangwuliu', '深圳德创物流');
INSERT INTO `express` VALUES (586, 'decnlh', '德中快递');
INSERT INTO `express` VALUES (587, 'dingdong', '叮咚快递');
INSERT INTO `express` VALUES (588, 'donghanwl', '东瀚物流');
INSERT INTO `express` VALUES (589, 'ecmsglobal', 'ECMS Express');
INSERT INTO `express` VALUES (590, 'edtexpress', 'e直运');
INSERT INTO `express` VALUES (591, 'egypt', '埃及（Egypt Post）');
INSERT INTO `express` VALUES (592, 'ethiopia', '埃塞俄比亚(Ethiopian postal)');
INSERT INTO `express` VALUES (593, 'eupackage', '易优包裹');
INSERT INTO `express` VALUES (594, 'feihukuaidi', '飞狐快递');
INSERT INTO `express` VALUES (595, 'finland', '芬兰(Itella Posti Oy)');
INSERT INTO `express` VALUES (596, 'fourpxus', '四方格');
INSERT INTO `express` VALUES (597, 'fsexp', '全速快递');
INSERT INTO `express` VALUES (598, 'gjwl', '冠捷物流 ');
INSERT INTO `express` VALUES (599, 'globaltracktrace', 'globaltracktrace');
INSERT INTO `express` VALUES (600, 'gtongsudi', '广通速递');
INSERT INTO `express` VALUES (601, 'gzanjcwl', '广州安能聚创物流');
INSERT INTO `express` VALUES (602, 'haiwaihuanqiu', '海外环球');
INSERT INTO `express` VALUES (603, 'hgy56', '环国运物流');
INSERT INTO `express` VALUES (604, 'huaqikuaiyun', '华企快运');
INSERT INTO `express` VALUES (605, 'hyytes', '恒宇运通');
INSERT INTO `express` VALUES (606, 'iceland', '冰岛(Iceland Post)');
INSERT INTO `express` VALUES (607, 'ilogen', 'logen路坚');
INSERT INTO `express` VALUES (608, 'ilyang', 'ILYANG');
INSERT INTO `express` VALUES (609, 'jamaicapost', '牙买加（Jamaica Post）');
INSERT INTO `express` VALUES (610, 'jieborne', '捷邦物流');
INSERT INTO `express` VALUES (611, 'ldxpres', '林道国际快递-英文');
INSERT INTO `express` VALUES (612, 'ledaexpress', '乐达全球速递');
INSERT INTO `express` VALUES (613, 'maxeedexpress', '澳洲迈速快递');
INSERT INTO `express` VALUES (614, 'mchy', '木春货运');
INSERT INTO `express` VALUES (615, 'minbangsudi', '民邦速递');
INSERT INTO `express` VALUES (616, 'mingliangwuliu', '明亮物流');
INSERT INTO `express` VALUES (617, 'mrw', 'MRW');
INSERT INTO `express` VALUES (618, 'myhermes', 'MyHermes');
INSERT INTO `express` VALUES (619, 'njhaobo', '浩博物流');
INSERT INTO `express` VALUES (620, 'nzzto', '新西兰中通');
INSERT INTO `express` VALUES (621, 'ontrac', 'OnTrac');
INSERT INTO `express` VALUES (622, 'parcelforcecn', '英国邮政大包EMS');
INSERT INTO `express` VALUES (623, 'peisihuoyunkuaidi', '配思货运');
INSERT INTO `express` VALUES (624, 'pfcexpress', '皇家物流');
INSERT INTO `express` VALUES (625, 'qesd', '7E速递');
INSERT INTO `express` VALUES (626, 'qskdyxgs', '千顺快递');
INSERT INTO `express` VALUES (627, 'quanjitong', '全际通');
INSERT INTO `express` VALUES (628, 'quansutong', '全速通');
INSERT INTO `express` VALUES (629, 'quantium', 'Quantium');
INSERT INTO `express` VALUES (630, 'shbwch', '杰响物流');
INSERT INTO `express` VALUES (631, 'shpostwish', 'wish邮');
INSERT INTO `express` VALUES (632, 'sinoairinex', '中外运空运');
INSERT INTO `express` VALUES (633, 'southafrican', '南非（South African Post Office）');
INSERT INTO `express` VALUES (634, 'subaoex', '速豹');
INSERT INTO `express` VALUES (635, 'supinexpress', '速品快递');
INSERT INTO `express` VALUES (636, 'swisspostcn', '瑞士邮政');
INSERT INTO `express` VALUES (637, 'tcxbthai', 'TCXB国际物流');
INSERT INTO `express` VALUES (638, 'tntpostcn', 'TNT Post');
INSERT INTO `express` VALUES (639, 'ukraine', '乌克兰小包、大包(UkrPoshta)');
INSERT INTO `express` VALUES (640, 'vipexpress', '鹰运国际速递');
INSERT INTO `express` VALUES (641, 'xingyuankuaidi', '新元快递');
INSERT INTO `express` VALUES (642, 'xtb', '鑫通宝物流');
INSERT INTO `express` VALUES (643, 'yatfai', '一辉物流');
INSERT INTO `express` VALUES (644, 'yemen', '也门(Yemen Post)');
INSERT INTO `express` VALUES (645, 'yishunhang', '亿顺航');
INSERT INTO `express` VALUES (646, 'yuefengwuliu', '越丰物流');
INSERT INTO `express` VALUES (647, 'yuezhongsh', '粤中国际货运代理（上海）有限公司');
INSERT INTO `express` VALUES (648, 'advancing', '安达信');
INSERT INTO `express` VALUES (649, 'afghan', '阿富汗(Afghan Post)');
INSERT INTO `express` VALUES (650, 'agopost', '全程快递');
INSERT INTO `express` VALUES (651, 'ahkbps', '卡邦配送');
INSERT INTO `express` VALUES (652, 'amcnorder', 'amazon-国内订单');
INSERT INTO `express` VALUES (653, 'amusorder', 'amazon-国际订单');
INSERT INTO `express` VALUES (654, 'auvexpress', 'AUV国际快递');
INSERT INTO `express` VALUES (655, 'bahrain', '巴林(Bahrain Post)');
INSERT INTO `express` VALUES (656, 'baotongkd', '宝通快递');
INSERT INTO `express` VALUES (657, 'baoxianda', '报通快递');
INSERT INTO `express` VALUES (658, 'bcwelt', 'BCWELT');
INSERT INTO `express` VALUES (659, 'bee001', '蜜蜂速递');
INSERT INTO `express` VALUES (660, 'belize', '伯利兹(Belize Postal)');
INSERT INTO `express` VALUES (661, 'bester', '飛斯特');
INSERT INTO `express` VALUES (662, 'bosind', '堡昕德速递');
INSERT INTO `express` VALUES (663, 'bqcwl', '百千诚物流');
INSERT INTO `express` VALUES (664, 'brazilposten', '巴西(Brazil Post/Correios)');
INSERT INTO `express` VALUES (665, 'byht', '展勤快递');
INSERT INTO `express` VALUES (666, 'caledonia', '新喀里多尼亚[法国](New Caledonia)');
INSERT INTO `express` VALUES (667, 'canpostfr', '加拿大邮政');
INSERT INTO `express` VALUES (668, 'ccd', '河南次晨达');
INSERT INTO `express` VALUES (669, 'changyuwuliu', '长宇物流');
INSERT INTO `express` VALUES (670, 'chinasqk', 'SQK国际速递');
INSERT INTO `express` VALUES (671, 'chronopostport', 'Chronopost Portugal');
INSERT INTO `express` VALUES (672, 'city56', '城市映急');
INSERT INTO `express` VALUES (673, 'cjkoreaexpress', '大韩通运');
INSERT INTO `express` VALUES (674, 'cncexp', 'C&C国际速递');
INSERT INTO `express` VALUES (675, 'cnws', '中国翼');
INSERT INTO `express` VALUES (676, 'correos', '哥斯达黎加(Correos de Costa Rica)');
INSERT INTO `express` VALUES (677, 'csxss', '新时速物流');
INSERT INTO `express` VALUES (678, 'cypruspost', '塞浦路斯(Cyprus Post)');
INSERT INTO `express` VALUES (679, 'dasu', '达速物流');
INSERT INTO `express` VALUES (680, 'dfpost', '达方物流');
INSERT INTO `express` VALUES (681, 'dhlhk', 'DHL HK');
INSERT INTO `express` VALUES (682, 'dhlnetherlands', 'DHL-荷兰（DHL Netherlands）');
INSERT INTO `express` VALUES (683, 'dhlpoland', 'DHL-波兰（DHL Poland）');
INSERT INTO `express` VALUES (684, 'dianyi', '云南滇驿物流');
INSERT INTO `express` VALUES (685, 'disifangus', '递四方美国');
INSERT INTO `express` VALUES (686, 'ecuador', '厄瓜多尔(Correos del Ecuador)');
INSERT INTO `express` VALUES (687, 'el56', '易联通达');
INSERT INTO `express` VALUES (688, 'emsukraine', '乌克兰EMS(EMS Ukraine)');
INSERT INTO `express` VALUES (689, 'england', '英国(大包,EMS)');
INSERT INTO `express` VALUES (690, 'estes', 'Estes');
INSERT INTO `express` VALUES (691, 'euguoji', '易邮国际');
INSERT INTO `express` VALUES (692, 'europeanecom', 'europeanecom');
INSERT INTO `express` VALUES (693, 'fastzt', '正途供应链');
INSERT INTO `express` VALUES (694, 'fbkd', '飞邦快递');
INSERT INTO `express` VALUES (695, 'fedexuk', 'FedEx-英国件（FedEx UK)');
INSERT INTO `express` VALUES (696, 'fedexukcn', 'FedEx-英国件');
INSERT INTO `express` VALUES (697, 'fedroad', 'FedRoad 联邦转运');
INSERT INTO `express` VALUES (698, 'fenghuangkuaidi', '凤凰快递');
INSERT INTO `express` VALUES (699, 'fox', 'FOX国际快递');
INSERT INTO `express` VALUES (700, 'freakyquick', 'FQ狂派速递');
INSERT INTO `express` VALUES (701, 'gatien', 'Gati-英文');
INSERT INTO `express` VALUES (702, 'gml', '英脉物流');
INSERT INTO `express` VALUES (703, 'goldjet', '高捷快运');
INSERT INTO `express` VALUES (704, 'greenland', '格陵兰[丹麦]（TELE Greenland A/S）');
INSERT INTO `express` VALUES (705, 'gscq365', '哥士传奇速递');
INSERT INTO `express` VALUES (706, 'gswtkd', '万通快递');
INSERT INTO `express` VALUES (707, 'guangdongtonglu', '广东通路');
INSERT INTO `express` VALUES (708, 'gzxingcheng', '贵州星程快递');
INSERT INTO `express` VALUES (709, 'haihongmmb', '海红for买卖宝');
INSERT INTO `express` VALUES (710, 'haimengsudi', '海盟速递');
INSERT INTO `express` VALUES (711, 'handboy', '汉邦国际速递');
INSERT INTO `express` VALUES (712, 'haoyoukuai', '好又快物流');
INSERT INTO `express` VALUES (713, 'haypost', '亚美尼亚(Haypost-Armenian Postal)');
INSERT INTO `express` VALUES (714, 'hengrui56', '恒瑞物流');
INSERT INTO `express` VALUES (715, 'hjs', '猴急送');
INSERT INTO `express` VALUES (716, 'hnfy', '飞鹰物流');
INSERT INTO `express` VALUES (717, 'hnqst', '河南全速通');
INSERT INTO `express` VALUES (718, 'hnssd56', '顺时达物流');
INSERT INTO `express` VALUES (719, 'homexpress', '居家通');
INSERT INTO `express` VALUES (720, 'hqtd', '环球通达 ');
INSERT INTO `express` VALUES (721, 'hrbzykd', '卓烨快递');
INSERT INTO `express` VALUES (722, 'hrvatska', '克罗地亚（Hrvatska Posta）');
INSERT INTO `express` VALUES (723, 'htongexpress', '华通快运');
INSERT INTO `express` VALUES (724, 'huandonglg', '环东物流');
INSERT INTO `express` VALUES (725, 'hungary', '匈牙利（Magyar Posta）');
INSERT INTO `express` VALUES (726, 'hyk', '上海昊宏国际货物');
INSERT INTO `express` VALUES (727, 'idada', '大达物流');
INSERT INTO `express` VALUES (728, 'iexpress', 'iExpress');
INSERT INTO `express` VALUES (729, 'italysad', 'Italy SDA');
INSERT INTO `express` VALUES (730, 'iyoungspeed', '驿扬国际速运');
INSERT INTO `express` VALUES (731, 'jcex', 'jcex');
INSERT INTO `express` VALUES (732, 'jiajiatong56', '佳家通货运');
INSERT INTO `express` VALUES (733, 'jordan', '约旦(Jordan Post)');
INSERT INTO `express` VALUES (734, 'jsexpress', '骏绅物流');
INSERT INTO `express` VALUES (735, 'juwu', '聚物物流');
INSERT INTO `express` VALUES (736, 'kerrytj', '嘉里大荣物流');
INSERT INTO `express` VALUES (737, 'krtao', '淘韩国际快递');
INSERT INTO `express` VALUES (738, 'kuaitao', '快淘快递');
INSERT INTO `express` VALUES (739, 'kxda', '凯信达');
INSERT INTO `express` VALUES (740, 'lanhukuaidi', '蓝弧快递');
INSERT INTO `express` VALUES (741, 'lbbk', '立白宝凯物流');
INSERT INTO `express` VALUES (742, 'ledii', '乐递供应链');
INSERT INTO `express` VALUES (743, 'libanpost', '黎巴嫩(Liban Post)');
INSERT INTO `express` VALUES (744, 'lithuania', '立陶宛（Lietuvos pa?tas）');
INSERT INTO `express` VALUES (745, 'lmfex', '良藤国际速递');
INSERT INTO `express` VALUES (746, 'lundao', '论道国际物流');
INSERT INTO `express` VALUES (747, 'luxembourg', '卢森堡(Luxembourg Post)');
INSERT INTO `express` VALUES (748, 'lwe', 'LWE');
INSERT INTO `express` VALUES (749, 'macedonia', '马其顿(Macedonian Post)');
INSERT INTO `express` VALUES (750, 'malta', '马耳他（Malta Post）');
INSERT INTO `express` VALUES (751, 'mapleexpress', '今枫国际快运');
INSERT INTO `express` VALUES (752, 'mauritius', '毛里求斯(Mauritius Post)');
INSERT INTO `express` VALUES (753, 'milkyway', '银河物流');
INSERT INTO `express` VALUES (754, 'mjexp', '美龙快递');
INSERT INTO `express` VALUES (755, 'moldova', '摩尔多瓦(Posta Moldovei)');
INSERT INTO `express` VALUES (756, 'montenegro', '黑山(Posta Crne Gore)');
INSERT INTO `express` VALUES (757, 'mxe56', '中俄速通（淼信）');
INSERT INTO `express` VALUES (758, 'nle', 'NLE');
INSERT INTO `express` VALUES (759, 'nlebv', '亚欧专线');
INSERT INTO `express` VALUES (760, 'novaposhta', 'Nova Poshta');
INSERT INTO `express` VALUES (761, 'nuoer', '诺尔国际物流');
INSERT INTO `express` VALUES (762, 'nuoyaao', '偌亚奥国际快递');
INSERT INTO `express` VALUES (763, 'omniva', '爱沙尼亚(Eesti Post)');
INSERT INTO `express` VALUES (764, 'opek', 'OPEK');
INSERT INTO `express` VALUES (765, 'pakistan', '巴基斯坦(Pakistan Post)');
INSERT INTO `express` VALUES (766, 'parcelchina', '诚一物流');
INSERT INTO `express` VALUES (767, 'peixingwuliu', '陪行物流');
INSERT INTO `express` VALUES (768, 'pengcheng', '鹏程快递');
INSERT INTO `express` VALUES (769, 'portugalctt', '葡萄牙（Portugal CTT）');
INSERT INTO `express` VALUES (770, 'portugalseur', 'Portugal Seur');
INSERT INTO `express` VALUES (771, 'postennorge', '挪威（Posten Norge）');
INSERT INTO `express` VALUES (772, 'quantwl', '全通快运');
INSERT INTO `express` VALUES (773, 'quanxintong', '全信通快递');
INSERT INTO `express` VALUES (774, 'qzx56', '全之鑫物流');
INSERT INTO `express` VALUES (775, 'rokin', '荣庆物流');
INSERT INTO `express` VALUES (776, 'rrthk', '日日通国际');
INSERT INTO `express` VALUES (777, 'samoa', '萨摩亚(Samoa Post)');
INSERT INTO `express` VALUES (778, 'scxingcheng', '四川星程快递');
INSERT INTO `express` VALUES (779, 'selektvracht', 'Selektvracht');
INSERT INTO `express` VALUES (780, 'serbia', '塞尔维亚(PE Post of Serbia)');
INSERT INTO `express` VALUES (781, 'shanghaiwujiangmmb', '上海无疆for买卖宝');
INSERT INTO `express` VALUES (782, 'shiningexpress', '阳光快递');
INSERT INTO `express` VALUES (783, 'shipsoho', '苏豪快递');
INSERT INTO `express` VALUES (784, 'shiyunkuaidi', '世运快递');
INSERT INTO `express` VALUES (785, 'shlexp', 'SHL畅灵国际物流');
INSERT INTO `express` VALUES (786, 'sinoex', '中外运速递-中文');
INSERT INTO `express` VALUES (787, 'skynetmalaysia', 'SkyNet Malaysia');
INSERT INTO `express` VALUES (788, 'skypost', '荷兰Sky Post');
INSERT INTO `express` VALUES (789, 'slpost', '斯里兰卡(Sri Lanka Post)');
INSERT INTO `express` VALUES (790, 'stzd56', '智德物流');
INSERT INTO `express` VALUES (791, 'sucheng', '速呈宅配');
INSERT INTO `express` VALUES (792, 'sucmj', '特急便物流');
INSERT INTO `express` VALUES (793, 'taijin', '泰进物流');
INSERT INTO `express` VALUES (794, 'tianzong', '天纵物流');
INSERT INTO `express` VALUES (795, 'timedg', '万家通快递');
INSERT INTO `express` VALUES (796, 'tntuk', 'TNT UK');
INSERT INTO `express` VALUES (797, 'turtle', '海龟国际快递');
INSERT INTO `express` VALUES (798, 'upsmailinno', 'UPS Mail Innovations');
INSERT INTO `express` VALUES (799, 'uzbekistan', '乌兹别克斯坦(Post of Uzbekistan)');
INSERT INTO `express` VALUES (800, 'vangenexpress', '万庚国际速递');
INSERT INTO `express` VALUES (801, 'vnpost', '越南EMS(VNPost Express)');
INSERT INTO `express` VALUES (802, 'wenjiesudi', '文捷航空');
INSERT INTO `express` VALUES (803, 'wlwex', '星空国际');
INSERT INTO `express` VALUES (804, 'wowvip', '沃埃家');
INSERT INTO `express` VALUES (805, 'wtdex', 'WTD海外通');
INSERT INTO `express` VALUES (806, 'wygj168', '万运国际快递');
INSERT INTO `express` VALUES (807, 'wzhaunyun', '微转运');
INSERT INTO `express` VALUES (808, 'xianchengliansudi', '西安城联速递');
INSERT INTO `express` VALUES (809, 'xiaocex', '小C海淘');
INSERT INTO `express` VALUES (810, 'ycgglobal', 'YCG物流');
INSERT INTO `express` VALUES (811, 'ydfexpress', '易达丰国际速递');
INSERT INTO `express` VALUES (812, 'yodel', 'YODEL');
INSERT INTO `express` VALUES (813, 'youlai', '邮来速递');
INSERT INTO `express` VALUES (814, 'yuanhhk', '远航国际快运');
INSERT INTO `express` VALUES (815, 'yunexpress', '德国云快递');
INSERT INTO `express` VALUES (816, 'yyqc56', '一运全成物流');
INSERT INTO `express` VALUES (817, 'zhongjiwuliu', '中技物流');
INSERT INTO `express` VALUES (818, 'zjgj56', '振捷国际货运');
INSERT INTO `express` VALUES (819, 'zsky123', '准实快运');
INSERT INTO `express` VALUES (820, 'zsmhwl', '明辉物流');
INSERT INTO `express` VALUES (821, 'adiexpress', '安达易国际速递');
INSERT INTO `express` VALUES (822, 'adlerlogi', '德国雄鹰速递');
INSERT INTO `express` VALUES (823, 'afl', 'AFL');
INSERT INTO `express` VALUES (824, 'ajlogistics', '澳捷物流');
INSERT INTO `express` VALUES (825, 'anjiatongcheng', '安家同城快运');
INSERT INTO `express` VALUES (826, 'anlexpress', '新干线快递');
INSERT INTO `express` VALUES (827, 'aosu', '澳速物流');
INSERT INTO `express` VALUES (828, 'apgecommerce', 'apgecommerce');
INSERT INTO `express` VALUES (829, 'aplus100', '美国汉邦快递');
INSERT INTO `express` VALUES (830, 'aplusex', 'Aplus物流');
INSERT INTO `express` VALUES (831, 'aruba', '阿鲁巴[荷兰]（Post Aruba）');
INSERT INTO `express` VALUES (832, 'auadexpress', '澳达国际物流');
INSERT INTO `express` VALUES (833, 'auex', '澳货通');
INSERT INTO `express` VALUES (834, 'ausbondexpress', '澳邦国际物流');
INSERT INTO `express` VALUES (835, 'axexpress', '澳新物流');
INSERT INTO `express` VALUES (836, 'azerbaijan', '阿塞拜疆EMS(EMS AzerExpressPost)');
INSERT INTO `express` VALUES (837, 'bangbangpost', '帮帮发');
INSERT INTO `express` VALUES (838, 'bangladesh', '孟加拉国(EMS)');
INSERT INTO `express` VALUES (839, 'barbados', '巴巴多斯(Barbados Post)');
INSERT INTO `express` VALUES (840, 'benniao', '笨鸟国际');
INSERT INTO `express` VALUES (841, 'bjxsrd', '鑫锐达');
INSERT INTO `express` VALUES (842, 'bljt56', '佰乐捷通');
INSERT INTO `express` VALUES (843, 'bluedart', 'BlueDart');
INSERT INTO `express` VALUES (844, 'bmlchina', '标杆物流');
INSERT INTO `express` VALUES (845, 'bohei', '波黑(JP BH Posta)');
INSERT INTO `express` VALUES (846, 'bolivia', '玻利维亚');
INSERT INTO `express` VALUES (847, 'borderguru', 'BorderGuru');
INSERT INTO `express` VALUES (848, 'botspost', '博茨瓦纳');
INSERT INTO `express` VALUES (849, 'bphchina', '速方(Sufast)');
INSERT INTO `express` VALUES (850, 'brunei', '文莱(Brunei Postal)');
INSERT INTO `express` VALUES (851, 'cambodia', '柬埔寨(Cambodia Post)');
INSERT INTO `express` VALUES (852, 'camekong', '到了港');
INSERT INTO `express` VALUES (853, 'campbellsexpress', 'Campbell’s Express');
INSERT INTO `express` VALUES (854, 'canhold', '能装能送');
INSERT INTO `express` VALUES (855, 'cargolux', '卢森堡航空');
INSERT INTO `express` VALUES (856, 'cbo56', '钏博物流');
INSERT INTO `express` VALUES (857, 'cdek', 'CDEK');
INSERT INTO `express` VALUES (858, 'cdjx56', '捷祥物流');
INSERT INTO `express` VALUES (859, 'cdxinchen56', '鑫宸物流');
INSERT INTO `express` VALUES (860, 'cevalogistics', 'CEVA Logistic');
INSERT INTO `express` VALUES (861, 'cex', '城铁速递');
INSERT INTO `express` VALUES (862, 'cfss', '银雁专送');
INSERT INTO `express` VALUES (863, 'changwooair', '昌宇国际');
INSERT INTO `express` VALUES (864, 'chengda', '成达国际速递');
INSERT INTO `express` VALUES (865, 'chengji', '城际快递');
INSERT INTO `express` VALUES (866, 'chengtong', '城通物流');
INSERT INTO `express` VALUES (867, 'chile', '智利(Correos Chile)');
INSERT INTO `express` VALUES (868, 'chinatzx', '同舟行物流');
INSERT INTO `express` VALUES (869, 'chllog', '嘉荣物流');
INSERT INTO `express` VALUES (870, 'chronopostfren', '法国大包、EMS-英文(Chronopost France)');
INSERT INTO `express` VALUES (871, 'citysprint', 'citysprint');
INSERT INTO `express` VALUES (872, 'cjqy', '长吉物流');
INSERT INTO `express` VALUES (873, 'cloudlogistics365', '群航国际物流');
INSERT INTO `express` VALUES (874, 'clsp', 'CL日中速运');
INSERT INTO `express` VALUES (875, 'cneulogistics', '中欧物流');
INSERT INTO `express` VALUES (876, 'cnup', 'CNUP 中联邮');
INSERT INTO `express` VALUES (877, 'correios', '莫桑比克（Correios de Moçambique）');
INSERT INTO `express` VALUES (878, 'correo', '乌拉圭（Correo Uruguayo）');
INSERT INTO `express` VALUES (879, 'cqxingcheng', '重庆星程快递');
INSERT INTO `express` VALUES (880, 'crossbox', '环旅快运');
INSERT INTO `express` VALUES (881, 'czwlyn', '云南诚中物流');
INSERT INTO `express` VALUES (882, 'dcs', 'DCS');
INSERT INTO `express` VALUES (883, 'deltec', 'Deltec Courier');
INSERT INTO `express` VALUES (884, 'desworks', '澳行快递');
INSERT INTO `express` VALUES (885, 'directlink', 'Direct Link');
INSERT INTO `express` VALUES (886, 'djy56', '天翔东捷运');
INSERT INTO `express` VALUES (887, 'donghong', '东红物流');
INSERT INTO `express` VALUES (888, 'dpduk', 'DPD UK');
INSERT INTO `express` VALUES (889, 'dtdcindia', 'DTDC India');
INSERT INTO `express` VALUES (890, 'duodao56', '多道供应链');
INSERT INTO `express` VALUES (891, 'ealceair', '东方航空物流');
INSERT INTO `express` VALUES (892, 'ecallturn', 'E跨通');
INSERT INTO `express` VALUES (893, 'ecfirstclass', 'EC-Firstclass');
INSERT INTO `express` VALUES (894, 'ecotransite', '东西E全运');
INSERT INTO `express` VALUES (895, 'edaeuexpress', '易达快运');
INSERT INTO `express` VALUES (896, 'edragon', '龙象国际物流');
INSERT INTO `express` VALUES (897, 'efspost', 'EFSPOST');
INSERT INTO `express` VALUES (898, 'eiffel', '艾菲尔国际速递');
INSERT INTO `express` VALUES (899, 'elta', '希腊包裹（ELTA Hellenic Post）');
INSERT INTO `express` VALUES (900, 'eltahell', '希腊EMS（ELTA Courier）');
INSERT INTO `express` VALUES (901, 'emiratesen', '阿联酋(Emirates Post)');
INSERT INTO `express` VALUES (902, 'emonitoringen', '波兰小包(Poczta Polska)');
INSERT INTO `express` VALUES (903, 'emssouthafrica', '南非EMS');
INSERT INTO `express` VALUES (904, 'emsukrainecn', '乌克兰EMS-中文(EMS Ukraine)');
INSERT INTO `express` VALUES (905, 'epspost', '联众国际');
INSERT INTO `express` VALUES (906, 'erqianjia56', '贰仟家物流');
INSERT INTO `express` VALUES (907, 'eshunda', '俄顺达');
INSERT INTO `express` VALUES (908, 'estafeta', 'Estafeta');
INSERT INTO `express` VALUES (909, 'eta100', '易达国际速递');
INSERT INTO `express` VALUES (910, 'eteenlog', 'ETEEN专线');
INSERT INTO `express` VALUES (911, 'eucnrail', '中欧国际物流');
INSERT INTO `express` VALUES (912, 'eucpost', '德国 EUC POST');
INSERT INTO `express` VALUES (913, 'europe8', '败欧洲');
INSERT INTO `express` VALUES (914, 'eusacn', '优莎速运');
INSERT INTO `express` VALUES (915, 'excocotree', '可可树美中速运');
INSERT INTO `express` VALUES (916, 'expressplus', '澳洲新干线快递');
INSERT INTO `express` VALUES (917, 'ezhuanyuan', '易转运');
INSERT INTO `express` VALUES (918, 'fandaguoji', '颿达国际快递-英文');
INSERT INTO `express` VALUES (919, 'fardarww', '颿达国际快递');
INSERT INTO `express` VALUES (920, 'fastontime', '加拿大联通快运');
INSERT INTO `express` VALUES (921, 'fengyee', '丰羿');
INSERT INTO `express` VALUES (922, 'fiji', '斐济(Fiji Post)');
INSERT INTO `express` VALUES (923, 'flowerkd', '花瓣转运');
INSERT INTO `express` VALUES (924, 'ftlexpress', '法翔速运');
INSERT INTO `express` VALUES (925, 'fyex', '飞云快递系统');
INSERT INTO `express` VALUES (926, 'gaotieex', '高铁快运');
INSERT INTO `express` VALUES (927, 'gatikwe', 'Gati-KWE');
INSERT INTO `express` VALUES (928, 'gdct56', '广东诚通物流');
INSERT INTO `express` VALUES (929, 'gdqwwl', '全网物流');
INSERT INTO `express` VALUES (930, 'gdrz58', '容智快运');
INSERT INTO `express` VALUES (931, 'gdxp', '新鹏快递');
INSERT INTO `express` VALUES (932, 'georgianpost', '格鲁吉亚(Georgian Pos）');
INSERT INTO `express` VALUES (933, 'ghl', '环创物流');
INSERT INTO `express` VALUES (934, 'ghtexpress', 'GHT物流');
INSERT INTO `express` VALUES (935, 'gibraltar', '直布罗陀[英国]( Royal Gibraltar Post)');
INSERT INTO `express` VALUES (936, 'global99', '全球特快');
INSERT INTO `express` VALUES (937, 'grivertek', '潍鸿');
INSERT INTO `express` VALUES (938, 'gtgogo', 'GT国际快运');
INSERT INTO `express` VALUES (939, 'guanting', '冠庭国际物流');
INSERT INTO `express` VALUES (940, 'guosong', '国送快运');
INSERT INTO `express` VALUES (941, 'gvpexpress', '宏观国际快递');
INSERT INTO `express` VALUES (942, 'gxwl', '光线速递');
INSERT INTO `express` VALUES (943, 'haixingqiao', '海星桥快递');
INSERT INTO `express` VALUES (944, 'haizhongzhuanyun', '海中转运');
INSERT INTO `express` VALUES (945, 'hanfengjl', '翰丰快递');
INSERT INTO `express` VALUES (946, 'hangyu', '航宇快递');
INSERT INTO `express` VALUES (947, 'happylink', '开心快递');
INSERT INTO `express` VALUES (948, 'hitaoe', 'Hi淘易快递');
INSERT INTO `express` VALUES (949, 'hlkytj', '互联快运');
INSERT INTO `express` VALUES (950, 'hlpgyl', '共联配');
INSERT INTO `express` VALUES (951, 'hnzqwl', '中强物流');
INSERT INTO `express` VALUES (952, 'hongjie', '宏捷国际物流');
INSERT INTO `express` VALUES (953, 'hongpinwuliu', '宏品物流');
INSERT INTO `express` VALUES (954, 'hotwms', '皇家云仓');
INSERT INTO `express` VALUES (955, 'hre', '高铁速递');
INSERT INTO `express` VALUES (956, 'hsgtsd', '海硕高铁速递');
INSERT INTO `express` VALUES (957, 'ht22', '海淘物流');
INSERT INTO `express` VALUES (958, 'htwd', '华通务达物流');
INSERT INTO `express` VALUES (959, 'huada', '华达快运');
INSERT INTO `express` VALUES (960, 'huaxiahuoyun', '华夏货运');
INSERT INTO `express` VALUES (961, 'humpline', '驼峰国际');
INSERT INTO `express` VALUES (962, 'huoban', '兰州伙伴物流');
INSERT INTO `express` VALUES (963, 'hutongwuliu', '户通物流');
INSERT INTO `express` VALUES (964, 'hyeship', '鸿远物流');
INSERT INTO `express` VALUES (965, 'hzpl', '华航快递');
INSERT INTO `express` VALUES (966, 'iex', '泛太优达');
INSERT INTO `express` VALUES (967, 'igcaexpress', '无限速递');
INSERT INTO `express` VALUES (968, 'imlb2c', '艾姆勒');
INSERT INTO `express` VALUES (969, 'indonesia', '印度尼西亚EMS(Pos Indonesia-EMS)');
INSERT INTO `express` VALUES (970, 'inposdom', '多米尼加（INPOSDOM – Instituto Postal Dominicano）');
INSERT INTO `express` VALUES (971, 'interlink', 'Interlink Express');
INSERT INTO `express` VALUES (972, 'iparcel', 'UPS i-parcel');
INSERT INTO `express` VALUES (973, 'iran', '伊朗（Iran Post）');
INSERT INTO `express` VALUES (974, 'jdexpressusa', '骏达快递');
INSERT INTO `express` VALUES (975, 'jdpplus', '急递');
INSERT INTO `express` VALUES (976, 'jerseypost', '泽西岛');
INSERT INTO `express` VALUES (977, 'jetexpressgroup', '澳速通国际速递');
INSERT INTO `express` VALUES (978, 'jiazhoumao', '加州猫速递');
INSERT INTO `express` VALUES (979, 'jinchengwuliu', '锦程物流');
INSERT INTO `express` VALUES (980, 'jintongkd', '劲通快递');
INSERT INTO `express` VALUES (981, 'jinyuekuaidi', '晋越快递');
INSERT INTO `express` VALUES (982, 'jisu', '冀速物流');
INSERT INTO `express` VALUES (983, 'jiugong', '九宫物流');
INSERT INTO `express` VALUES (984, 'jiuyicn', '久易快递');
INSERT INTO `express` VALUES (985, 'jixiangyouau', '吉祥邮（澳洲）');
INSERT INTO `express` VALUES (986, 'jjx888', '佳捷翔物流');
INSERT INTO `express` VALUES (987, 'juzhongda', '聚中大');
INSERT INTO `express` VALUES (988, 'kenya', '肯尼亚(POSTA KENYA)');
INSERT INTO `express` VALUES (989, 'keypon', '启邦国际物流');
INSERT INTO `express` VALUES (990, 'kjde', '跨境直邮通');
INSERT INTO `express` VALUES (991, 'koali', '番薯国际货运');
INSERT INTO `express` VALUES (992, 'kuai8', '快8速运');
INSERT INTO `express` VALUES (993, 'kuaiyouda', '四川快优达速递');
INSERT INTO `express` VALUES (994, 'kyrgyzpost', '吉尔吉斯斯坦(Kyrgyz Post)');
INSERT INTO `express` VALUES (995, 'kyue', '跨跃国际');
INSERT INTO `express` VALUES (996, 'lanbiaokuaidi', '蓝镖快递');
INSERT INTO `express` VALUES (997, 'lao', '老挝(Lao Express) ');
INSERT INTO `express` VALUES (998, 'laposte', '塞内加尔');
INSERT INTO `express` VALUES (999, 'lasy56', '林安物流');
INSERT INTO `express` VALUES (1000, 'latviaen', '拉脱维亚(Latvijas Pasts)');
INSERT INTO `express` VALUES (1001, 'lesotho', '莱索托(Lesotho Post)');
INSERT INTO `express` VALUES (1002, 'letseml', '美联快递');
INSERT INTO `express` VALUES (1003, 'lgs', 'lazada');
INSERT INTO `express` VALUES (1004, 'lhexpressus', '联合速递');
INSERT INTO `express` VALUES (1005, 'lianyun', '联运快递');
INSERT INTO `express` VALUES (1006, 'linex', 'Linex');
INSERT INTO `express` VALUES (1007, 'lishi', '丽狮物流');
INSERT INTO `express` VALUES (1008, 'littlebearbear', '小熊物流');
INSERT INTO `express` VALUES (1009, 'lnet', '新易泰');
INSERT INTO `express` VALUES (1010, 'logistics', '華信物流WTO');
INSERT INTO `express` VALUES (1011, 'longlangkuaidi', '隆浪快递');
INSERT INTO `express` VALUES (1012, 'longvast', '长风物流');
INSERT INTO `express` VALUES (1013, 'lsexpress', '6LS EXPRESS');
INSERT INTO `express` VALUES (1014, 'ltparcel', '联通快递');
INSERT INTO `express` VALUES (1015, 'luxembourgde', '卢森堡(Luxembourg Post)');
INSERT INTO `express` VALUES (1016, 'luxembourgfr', '卢森堡(Luxembourg Post)');
INSERT INTO `express` VALUES (1017, 'mailikuaidi', '麦力快递');
INSERT INTO `express` VALUES (1018, 'mailongdy', '迈隆递运');
INSERT INTO `express` VALUES (1019, 'mangguo', '芒果速递');
INSERT INTO `express` VALUES (1020, 'meibang', '美邦国际快递');
INSERT INTO `express` VALUES (1021, 'meidaexpress', '美达快递');
INSERT INTO `express` VALUES (1022, 'meitai', '美泰物流');
INSERT INTO `express` VALUES (1023, 'mexico', '墨西哥（Correos de Mexico）');
INSERT INTO `express` VALUES (1024, 'mexicodenda', 'Mexico Senda Express');
INSERT INTO `express` VALUES (1025, 'mongolpost', '蒙古国(Mongol Post) ');
INSERT INTO `express` VALUES (1026, 'morocco', '摩洛哥 ( Morocco Post )');
INSERT INTO `express` VALUES (1027, 'multipack', 'Mexico Multipack');
INSERT INTO `express` VALUES (1028, 'nalexpress', '新亚物流');
INSERT INTO `express` VALUES (1029, 'namibia', '纳米比亚(NamPost)');
INSERT INTO `express` VALUES (1030, 'nedahm', '红马速递');
INSERT INTO `express` VALUES (1031, 'nepalpost', '尼泊尔（Nepal Postal Services）');
INSERT INTO `express` VALUES (1032, 'nigerianpost', '尼日利亚(Nigerian Postal)');
INSERT INTO `express` VALUES (1033, 'niuzaiexpress', '牛仔速运');
INSERT INTO `express` VALUES (1034, 'nmhuahe', '华赫物流');
INSERT INTO `express` VALUES (1035, 'ocaargen', 'OCA Argentina');
INSERT INTO `express` VALUES (1036, 'ocpost', 'OC-Post');
INSERT INTO `express` VALUES (1037, 'oman', '阿曼(Oman Post)');
INSERT INTO `express` VALUES (1038, 'onway', '昂威物流');
INSERT INTO `express` VALUES (1039, 'overseaex', '波音速递');
INSERT INTO `express` VALUES (1040, 'paraguay', '巴拉圭(Correo Paraguayo)');
INSERT INTO `express` VALUES (1041, 'pcwl56', '普畅物流');
INSERT INTO `express` VALUES (1042, 'pdstow', '全球速递');
INSERT INTO `express` VALUES (1043, 'peex', '派尔快递');
INSERT INTO `express` VALUES (1044, 'pinsuxinda', '品速心达快递');
INSERT INTO `express` VALUES (1045, 'pinxinkuaidi', '品信快递');
INSERT INTO `express` VALUES (1046, 'pioneer', '先锋国际快递');
INSERT INTO `express` VALUES (1047, 'pmt0704be', '龙行天下');
INSERT INTO `express` VALUES (1048, 'portugalctten', '葡萄牙（Portugal CTT）');
INSERT INTO `express` VALUES (1049, 'posta', '坦桑尼亚（Tanzania Posts Corporation）');
INSERT INTO `express` VALUES (1050, 'postelbe', 'PostElbe');
INSERT INTO `express` VALUES (1051, 'postenab', 'PostNord(Posten AB)');
INSERT INTO `express` VALUES (1052, 'postpng', '巴布亚新几内亚(PNG Post)');
INSERT INTO `express` VALUES (1053, 'ptt', '土耳其');
INSERT INTO `express` VALUES (1054, 'qdants', 'ANTS EXPRESS');
INSERT INTO `express` VALUES (1055, 'qhxykd', '雪域快递');
INSERT INTO `express` VALUES (1056, 'qianli', '千里速递');
INSERT INTO `express` VALUES (1057, 'qichen', '启辰国际速递');
INSERT INTO `express` VALUES (1058, 'redexpress', 'Red Express');
INSERT INTO `express` VALUES (1059, 'rhtexpress', '睿和泰速运');
INSERT INTO `express` VALUES (1060, 'riyuwuliu', '日昱物流');
INSERT INTO `express` VALUES (1061, 'romanian', '罗马尼亚（Posta Romanian）');
INSERT INTO `express` VALUES (1062, 'ruidianyouzhengen', '瑞典（Sweden Post）');
INSERT INTO `express` VALUES (1063, 'rwanda', '卢旺达(Rwanda i-posita)');
INSERT INTO `express` VALUES (1064, 'safexpress', 'Safexpress');
INSERT INTO `express` VALUES (1065, 'sanshengco', '三盛快递');
INSERT INTO `express` VALUES (1066, 'saudipost', '沙特阿拉伯(Saudi Post)');
INSERT INTO `express` VALUES (1067, 'scic', '中加国际快递');
INSERT INTO `express` VALUES (1068, 'scsujiada', '速佳达快运');
INSERT INTO `express` VALUES (1069, 'sczpds', '速呈');
INSERT INTO `express` VALUES (1070, 'seur', 'International Seur');
INSERT INTO `express` VALUES (1071, 'sfau', '澳丰速递');
INSERT INTO `express` VALUES (1072, 'sfift', '十方通物流');
INSERT INTO `express` VALUES (1073, 'sfjhd', '圣飞捷快递');
INSERT INTO `express` VALUES (1074, 'shanda56', '衫达快运');
INSERT INTO `express` VALUES (1075, 'shanghaikuaitong', '上海快通');
INSERT INTO `express` VALUES (1076, 'shangtuguoji', '尚途国际货运');
INSERT INTO `express` VALUES (1077, 'shaoke', '捎客物流');
INSERT INTO `express` VALUES (1078, 'shd56', '商海德物流');
INSERT INTO `express` VALUES (1079, 'shengtongscm', '盛通快递');
INSERT INTO `express` VALUES (1080, 'shenjun', '神骏物流');
INSERT INTO `express` VALUES (1081, 'shenma', '神马快递');
INSERT INTO `express` VALUES (1082, 'shipbyace', '王牌快递');
INSERT INTO `express` VALUES (1083, 'shlindao', '林道国际快递');
INSERT INTO `express` VALUES (1084, 'shunbang', '顺邦国际物流');
INSERT INTO `express` VALUES (1085, 'shunshid', '顺士达速运');
INSERT INTO `express` VALUES (1086, 'sihaiet', '四海快递');
INSERT INTO `express` VALUES (1087, 'sihiexpress', '四海捷运');
INSERT INTO `express` VALUES (1088, 'siodemka', 'Siodemka');
INSERT INTO `express` VALUES (1089, 'sixroad', '易普递');
INSERT INTO `express` VALUES (1090, 'skynet', 'skynet');
INSERT INTO `express` VALUES (1091, 'skynetworldwide', 'skynetworldwide');
INSERT INTO `express` VALUES (1092, 'slovak', '斯洛伐克(Slovenská Posta)');
INSERT INTO `express` VALUES (1093, 'speeda', '行必达');
INSERT INTO `express` VALUES (1094, 'speedoex', '申必达');
INSERT INTO `express` VALUES (1095, 'speedpost', '新加坡EMS、大包(Singapore Speedpost)');
INSERT INTO `express` VALUES (1096, 'starex', '星速递');
INSERT INTO `express` VALUES (1097, 'staryvr', '星运快递');
INSERT INTO `express` VALUES (1098, 'stonewzealand', '申通新西兰');
INSERT INTO `express` VALUES (1099, 'sudapost', '苏丹（Sudapost）');
INSERT INTO `express` VALUES (1100, 'sujievip', '郑州速捷');
INSERT INTO `express` VALUES (1101, 'superoz', '速配欧翼');
INSERT INTO `express` VALUES (1102, 'sxexpress', '三象速递');
INSERT INTO `express` VALUES (1103, 'szdpex', '深圳DPEX');
INSERT INTO `express` VALUES (1104, 'taimek', '天美快递');
INSERT INTO `express` VALUES (1105, 'tanzania', '坦桑尼亚(Tanzania Posts)');
INSERT INTO `express` VALUES (1106, 'tcixps', 'TCI XPS');
INSERT INTO `express` VALUES (1107, 'tdcargo', 'TD Cargo');
INSERT INTO `express` VALUES (1108, 'thunderexpress', '加拿大雷霆快递');
INSERT INTO `express` VALUES (1109, 'tianxiang', '天翔快递');
INSERT INTO `express` VALUES (1110, 'tlky', '天联快运');
INSERT INTO `express` VALUES (1111, 'tmg', '株式会社T.M.G');
INSERT INTO `express` VALUES (1112, 'tntitaly', 'TNT Italy');
INSERT INTO `express` VALUES (1113, 'tny', 'TNY物流');
INSERT INTO `express` VALUES (1114, 'tonghetianxia', '通和天下');
INSERT INTO `express` VALUES (1115, 'topshey', '顶世国际物流');
INSERT INTO `express` VALUES (1116, 'tywl99', '天翼物流');
INSERT INTO `express` VALUES (1117, 'uex', 'UEX国际物流');
INSERT INTO `express` VALUES (1118, 'uexiex', '欧洲UEX');
INSERT INTO `express` VALUES (1119, 'uganda', '乌干达(Posta Uganda)');
INSERT INTO `express` VALUES (1120, 'ugoexpress', '邮鸽速运');
INSERT INTO `express` VALUES (1121, 'upsfreight', 'UPS Freight');
INSERT INTO `express` VALUES (1122, 'uschuaxia', '华夏国际速递');
INSERT INTO `express` VALUES (1123, 'utaoscm', 'UTAO优到');
INSERT INTO `express` VALUES (1124, 'vanuatu', '瓦努阿图(Vanuatu Post)');
INSERT INTO `express` VALUES (1125, 'vctrans', '越中国际物流');
INSERT INTO `express` VALUES (1126, 'wanboex', '万博快递');
INSERT INTO `express` VALUES (1127, 'wanjiatong', '宁夏万家通');
INSERT INTO `express` VALUES (1128, 'wdm', '万达美');
INSERT INTO `express` VALUES (1129, 'wexpress', '威速递');
INSERT INTO `express` VALUES (1130, 'whgjkd', '香港伟豪国际物流');
INSERT INTO `express` VALUES (1131, 'wlfast', '凡仕特物流');
INSERT INTO `express` VALUES (1132, 'xdshipping', '国晶物流');
INSERT INTO `express` VALUES (1133, 'xflt56', '蓝天物流');
INSERT INTO `express` VALUES (1134, 'xhf56', '鑫宏福物流');
INSERT INTO `express` VALUES (1135, 'xiangdawuliu', '湘达物流');
INSERT INTO `express` VALUES (1136, 'xinning', '新宁物流');
INSERT INTO `express` VALUES (1137, 'xipost', '西邮寄');
INSERT INTO `express` VALUES (1138, 'xsrd', '鑫世锐达');
INSERT INTO `express` VALUES (1139, 'xyjexpress', '西游寄速递');
INSERT INTO `express` VALUES (1140, 'yamaxunwuliu', '亚马逊中国');
INSERT INTO `express` VALUES (1141, 'yifankd', '艺凡快递');
INSERT INTO `express` VALUES (1142, 'yihangmall', '易航物流');
INSERT INTO `express` VALUES (1143, 'yilingsuyun', '亿领速运');
INSERT INTO `express` VALUES (1144, 'yitongda', '易通达');
INSERT INTO `express` VALUES (1145, 'ytky168', '运通快运');
INSERT INTO `express` VALUES (1146, 'zhdwl', '众辉达物流');
INSERT INTO `express` VALUES (1147, 'zhonghongwl', '中宏物流');
INSERT INTO `express` VALUES (1148, 'zhpex', '众派速递');

SET FOREIGN_KEY_CHECKS = 1;
