<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use App\Models\ModelAbstract;
use Dcat\Admin\Traits\HasDateTimeFormatter;
/**
 * Class Setting
 * @package App\Models
 * @property string id
 * @property string title
 * @property integer type
 * @property string alias
 * @property string value
 * @property Carbon created_at
 * @property Carbon updated_at
 * @property Carbon deleted_at
 */
class Setting extends ModelAbstract {

    use SoftDeletes;
    use HasDateTimeFormatter;

    const TYPE_STRING = 1;
    const TYPE_IMG = 2;
    const TYPE_TEXT = 3;
    const TYPE_NUM = 4;
    const TYPE_VIDEO = 5;

    public static $type_all = [
        self::TYPE_STRING,
        self::TYPE_IMG,
        self::TYPE_TEXT,
        self::TYPE_NUM,
        self::TYPE_VIDEO,
    ];

    public static $type_maps = [
        self::TYPE_STRING => '字符串',
        self::TYPE_IMG => '图片',
        self::TYPE_TEXT => '富文本',
        self::TYPE_NUM => '数字',
        self::TYPE_VIDEO => '视频',
    ];
    protected $table = "setting";

    protected $fillable = [
        'id',
        'type',
        'alias',
        'value',
        'title',
    ];

    protected $casts = [
        'id' => 'string',
        'type' => 'string',
        'title' => 'string',
        'alias' => 'string',
        'value' => 'string',
        'deleted_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
    public function save(array $options = [])
    {

        if($this->getAttributeFromArray('value1')){
            $this->setAttribute('value',$this->getAttributeFromArray('value1'));

        }elseif ($this->getAttributeFromArray('value2')){
            $this->setAttribute('value',$this->getAttributeFromArray('value2'));

        }elseif ($this->getAttributeFromArray('value3')){
            $this->setAttribute('value',$this->getAttributeFromArray('value3'));

        }elseif ($this->getAttributeFromArray('value4')){
            $this->setAttribute('value',$this->getAttributeFromArray('value4'));

        }elseif ($this->getAttributeFromArray('value5')){
            $this->setAttribute('value',$this->getAttributeFromArray('value5'));

        }
        unset($this->value1);
        unset($this->value2);
        unset($this->value3);
        unset($this->value4);
        unset($this->value5);
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
